server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 60000
      max-lifetime: 1800000
      idle-timeout: 600000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      poll-interval: 200ms
      quiet-period: 100ms
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
      database: ${REDIS_DATABASE}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
      timeout: ${REDIS_TIMEOUT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: Authentication service
    description: Authentication service to manage user information

jwt:
  secret-string: ${JWT_SECRET_STRING}
  expiration-millis: ${JWT_EXPIRATION_MILLIS}

frontend-url: ${FRONTEND_URL}

app:
  cache:
    default-ttl-minutes: ${CACHE_DEFAULT_TTL_MINUTES}