server:
  port: ${SERVER_PORT}

spring:
  datasource:
    form-data-service:
      jdbcUrl: ${FORM_DATA_SERVICE_DB_URL}
      username: ${FORM_DATA_SERVICE_DB_USERNAME}
      password: ${FORM_DATA_SERVICE_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    form-schema:
      jdbcUrl: ${FORM_SCHEMA_DB_URL}
      username: ${FORM_SCHEMA_DB_USERNAME}
      password: ${FORM_SCHEMA_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      poll-interval: 200ms
      quiet-period: 100ms

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: Form data service
    description: Form data service to manage form data