server:
  port: ${SERVER_PORT}

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: Gateway service
    description: API Gateway service